apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io   # ensures resources get pruned if you delete the App
spec:
  project: default
  source:
    repoURL: https://github.com/joindevops-1/argocd.git
    targetRevision: main
    path: .                                    # change if your chart is not at repo root
    helm:
      releaseName: frontend
      valueFiles:
        - values.yaml                          # or values-prod.yaml per env
  destination:
    server: https://kubernetes.default.svc
    namespace: roboshop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
  revisionHistoryLimit: 10
  ignoreDifferences:                            # avoids false drift if mutating webhooks add pod annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations
